name: pipeline
on:
 push:
   branches:
     - "main"

permissions:
  packages: write

jobs:
  build-and-deploy:
    environment:
      name: development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Package the application
        run: |
          mkdir -p dist
          tar -czf dist/sensepro-controller-${{ github.sha }}.tar.gz main.py deploy_service.sh
          echo "Package created: dist/sensepro-controller.tar.gz"

      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:dev-ci

      - name: Test Hostname Resolution
        run: |
          ping -c 3 raspberrypi || (echo "Hostname resolution failed!" && exit 1)
          nc -zv raspberrypi 22 || (echo "Port 22 is not accessible!" && exit 1)

      - name: Prepare SSH Directory
        run: |
          mkdir -p ~/.ssh
          chmod 0700 ~/.ssh
          ssh-keyscan -p "22" -H "raspberrypi" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: ssh -o ConnectTimeout=30 "pi@raspberrypi" "echo 'SSH connection successful!'"

      - name: Deploy to DEV
        env:
          RABBITMQ_USER: ${{ secrets.RABBITMQ_USER }}
          RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
        run: |
          ssh "pi@raspberrypi" "mkdir -p /opt/sensepro-controller"
          scp dist/sensepro-controller-${{ github.sha }}.tar.gz pi@raspberrypi:/tmp
          ssh "pi@raspberrypi" "tar -xzf /tmp/sensepro-controller-${{ github.sha }}.tar.gz -C /opt/sensepro-controller"
          ssh "pi@raspberrypi" "RABBITMQ_USER=$RABBITMQ_USER RABBITMQ_PASSWORD=$RABBITMQ_PASSWORD bash /opt/sensepro-controller/deploy_service.sh"
          ssh "pi@raspberrypi" "rm -rf /tmp/sensepro-controller-${{ github.sha }}.tar.gz"
